name: SlashFortifier
main: windyroad.slashfortifier.main.Main
version: 1.0.0
commands:
    slashfortifier:
        description: Itemizer menu
        usage: /slashfortifier <args>
    sff:
        description: Itemizer menu
        usage: /sff <args>